title: Fotorelacjonusz

description: >-
  A community tool for posting photo reports to skyscrapercity.com.

author:
  name: Sebastian Skałacki

url: "https://fotorelacjonusz.github.io"

avatar: "assets/rounded.png"

github_username:  fotorelacjonusz

download_link: https://github.com/fotorelacjonusz/fotorelacjonusz-ng/releases/latest

markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
      css: assets/css/fotorelacjonusz.css
      show-avatar: true

# Replace with daattali/beautiful-jekyll when following is resolved:
# https://github.com/daattali/beautiful-jekyll/issues/339
remote_theme: gpotter2/beautiful-jekyll

plugins:
  - jekyll-asciidoc
  - jekyll-remote-theme
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
