title: Fotorelacjonusz

# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

author:
  name: Sebastian Skałacki

url: "https://fotorelacjonusz.github.io"

avatar: "assets/rounded.png"

github_username:  fotorelacjonusz

markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
      show-avatar: true

# Replace with daattali/beautiful-jekyll when following is resolved:
# https://github.com/daattali/beautiful-jekyll/issues/339
remote_theme: gpotter2/beautiful-jekyll

plugins:
  - jekyll-asciidoc
  - jekyll-remote-theme
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
