---
layout: page
title: Fotorelacjonusz
subtitle: A community tool for posting photo reports to skyscrapercity.com
---

Fotorelacjonusz is free software distributed under the terms of the GNU General
Public License version 3 or (at your option) any later version.

=== Installation instructions

On Linux, you may want to download a DEB or RPM package, and then install it
with your system package manager.  Alternatively, you may download the TAR.GZ
archive and unpack it to a preferred location.

On macOS, unpack the downloaded ZIP file.  It contains an application bundle,
which you may move to Applications directory if you want to.  Make sure that
your system settings allow for running software from outside of App Store.

On Windows, unpack the downloaded ZIP file.  The executable is inside extracted
directory.  Don't move your files around, or it won't work.  There is no nice
installer (yet), unfortunately, but help is welcome.

=== More details & source code

See https://github.com/fotorelacjonusz/fotorelacjonusz-ng[GitHub] repository.

=== Get involved

A lot can be improved.  Suggestions and pull requests are welcome.

=== Adopt to your own forum

Why not?  This is a free software.

=== Thanks

Many thanks to Kamil OST, who wrote the original C++ version of
Fotorelacjonusz;
to https://github.com/marteczek/[MariuszLu] and his Friend, who contributed
the program icon;
and to everyone who posts photo reports with or without help of this program.
